import * as image from "../../assets/mentors/index"

export const DataMentors = [  
  {
    id: 1,
    name: "António Muteka",
    profession: "UI UX Design",
    description: "Hi, I'm Jessica Jane. I am a doctoral student at Harvard University majoring in Web . . . ",
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 2,
    name: "Domingos Matumona",
    profession: "UI UX Design",
    description: "Hi, I'm Alex Stanton. I am a doctoral student at Oxford University majoring in UI / UX  . . . ",
    imageProfile: image.MentorImage2,
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 3,
    name: "Luís Carlos Baptista",
    profession: "UI UX Design",
    description: "Hi, I'm Antoine Griezmann. I'm an Android Developer at Google company . . .",
    imageProfile: image.MentorImage3,
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 4,
    name: "Domingas Quissanga",
    profession: "UI UX Design",
    description: "Hi, I'm Anna White. I'm a professional 3D Designer at Blender company . . .",
    imageProfile: image.MentorImage4,
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 5,
    name: "Dário Manuel Pinto",
    profession: "UI UX Design",
    description: "Hi, I'm Richard Kyle. I'm a professional 2D Designer at Photoshop company . . .",
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 6,
    name: "Joel Marcolino",
    profession: "UI UX Design",
    description: "Hi, I'm Julia Philips. I'm a senior manager at Apple company . . .",
    imageProfile: image.MentorImage6,
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 7,
    name: "Paulo André",
    profession: "UI UX Design",
    description: "Front-End Developer...",
    imageProfile: image.MentorImage7,
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 8,
    name: "Efraim Luzayamo",
    profession: "UI UX Design",
    description: "Front-End Developer...",
    imageProfile: image.MentorImage8,
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 9,
    name: "Pedro Lutete",
    profession: "UI UX Design",
    description: "Front-End Developer...",
    imageProfile: image.MentorImage1,
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 10,
    name: "Ana Camila",
    profession: "UI UX Design",
    description: "Front-End Developer...",
    imageProfile: image.MentorImage5,
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
];
