import { ImageProfile } from "../../assets/header";
export const DataMentors = [  
  {
    id: 1,
    name: "Curious George André",
    profession: "UI UX Design",
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 2,
    name: "Curious George",
    profession: "UI UX Design",
    imageProfile: ImageProfile,
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 3,
    name: "Curious George",
    profession: "UI UX Design",
    imageProfile: ImageProfile,
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 4,
    name: "Curious George",
    profession: "UI UX Design",
    imageProfile: ImageProfile,
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 5,
    name: "Curious George",
    profession: "UI UX Design",
    imageProfile: ImageProfile,
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 6,
    name: "Curious George",
    profession: "UI UX Design",
    imageProfile: ImageProfile,
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
  {
    id: 7,
    name: "Curious George",
    profession: "UI UX Design",
    imageProfile: ImageProfile,
    taskQuantity: "40 Task",
    rating: "4.7 (750 Reviews)",
  },
];
